name: Workflow

on:
  workflow_dispatch:
  push:

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.SECRET }}
      - run: echo ${{ vars.FOO }}
      - uses: david-haerer/action/action1@main